# Generated by Django 6.0.3 on 2026-03-30 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawling', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crawlrawdata',
            name='item_url',
            field=models.URLField(blank=True, max_length=2000),
        ),
    ]
