# Generated by Django 6.0.3 on 2026-03-30 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawling', '0006_alter_crawljoblog_command_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crawlrawdata',
            name='item_url',
            field=models.URLField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='crawlrawdata',
            name='source_url',
            field=models.URLField(max_length=2000),
        ),
    ]
